NODES:
  gpu3:
    ip: 192.168.3.113
    user: liuzili

  gpu4:
    ip: 192.168.3.114
    user: liuzili

  gpu7:
    ip: 192.168.3.117
    user: liuzili

  gpu9:
    ip: 192.168.3.119
    user: liuzili

  gpu11:
    ip: 192.168.3.121
    user: liuzili

  gpu13:
    ip: 192.168.3.123
    user: liuzili

  gpu15:
    ip: 192.168.3.125
    user: liuzili
